services:

  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
    - ./schema/:/docker-entrypoint-initdb.d
    - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
     - myserver

  app:
    container_name: vk_app
    build: ./
    command: ./wait-for-postgres.sh db ./app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    networks:
     - myserver

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
     - myserver

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=stacysv17
      - GF_SECURITY_ADMIN_PASSWORD=b!n6H7!zekMYwjA
    depends_on:
      - prometheus
    networks:
      - myserver

volumes:
  pg-data:
  grafana-data:

networks:
  myserver:
    driver: bridge